apiVersion: v1
kind: Service
metadata:
  name: astraflow-service
  labels:
    app: astraflow-service
    managed-by: astraflow
spec:
  type: LoadBalancer
  selector:
    app: astraflow-service
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  sessionAffinity: None
